### ISSUE TITLE
When decoding MUSCLE does not write to temp_batch_output.fasta, resulting in decoding failure

### ISSUE THREAD

**Issue by Grey-Gong** [ysfhtxn/Composite-Hedges-Nanopores#1]
I did run this program in linux (UBUNTU 20.04), and the followings are the exact errors:
![微信图片_20241112221019](https://github.com/user-attachments/assets/54629515-2731-4685-8ea4-742e0bedb12c)
Looking forward to your reply！Thanks！

**Comment by Taltalite** [comment]
> I did run this program in linux (UBUNTU 20.04), and the followings are the exact errors: ![微信图片_20241112221019](https://private-user-images.githubusercontent.com/175175126/385317144-54629515-2731-4685-8ea4-742e0bedb12c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0ODQ2MzUsIm5iZiI6MTczMTQ4NDMzNSwicGF0aCI6Ii8xNzUxNzUxMjYvMzg1MzE3MTQ0LTU0NjI5NTE1LTI3MzEtNDY4NS04ZWE0LTc0MmUwYmVkYjEyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QwNzUyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZGUzY2I3OWE4Y2QxMzM2OGIxMzk3MTA3MTc3MjMxNjVmNTE5MDZhNTU1YmM0MzE2YTJkYjcxNzU2MjkxOGMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KZ2mt_ychzcY43ip4RCOfjgf0Fwfc9BAuhqcD-REkd0) Looking forward to your reply！Thanks！

We found the same error when the MUSCLE did not be configured correctly. Please ensure the MUSCLE is downloaded and is set into the system PATH. 
For instance, if you download the file named `muscle-linux-x86.v5.1` , you may add the dir into the file _.bashrc_. **And importantly you should change the MUSCLE execution file name to `muscle`** which our code call this name to run MUSCLE.

To check whether the MUSCLE is configured correctly, you can type `muscle` in the command line and see the response.

**Comment by Grey-Gong** [comment]
Many thanks! The problem is solved.
